development:
  adapter: postgresql
  encoding: unicode
  database: trentonbahr_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: trentonbahr_test
  pool: 5
  username: postgres
  password: password
